webapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :courses do
    resources :reviews
  end
  
  root 'home#index' #sets homepage
  
  
end

webapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

webapp/app/models/course.rb
class Course < ApplicationRecord
    has_many :reviews
    
end

webapp/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :course
end

webapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

webapp/app/controllers/courses_controller.rb
#Cucumber Test:  1 - The user has the ability to create an account

#@when “User enters email “ThisIsATest@uncc.edu”.”
#@when “User enters password “Testing123!”.”
#@then “The user has created a valid account.”

#Cucumber Test:  2 - The user has the ability to log in

#@when “The user has a valid account.”
#@when “User enters email “ThisIsATest@uncc.edu”.”
#@when “User enters password “Testing123!”.”
#@then “The user has logged into a valid account a valid account.”




class CoursesController < ApplicationController
    def index
        @courses = Course.all
    end
    
    def new #by convention new action is associated with view, points to new view
        @course = Course.new
    end
    
    
    def create
        #render plain: params[:course].inspect #'render plain' - simply renders to the browser. 'params.[course].inspect' – accesses all parameters sent from the form
        @course = Course.new(course_params)
        if @course.save
            redirect_to @course
        else
            render 'new'
        end
    end
    
    def show
        @course = Course.find(params[:id])
    end
end

private
    def course_params
        params.require(:course).permit(:course_name)
    end

webapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

webapp/app/controllers/reviews_controller.rb
#Cucumber Test:  4 - The user has the ability to leave a review. 

#@when “The user has a valid account and is logged in ”
#@when “user selects the professor’s name “Marlon Mejias.”
#@when “user selects course rating of 9”
#@when “user selects overall rating of 9”
#@when “user selects programming language of “Ruby” ”
#@when “user does not select Textbook required”
#@when “user selects is computer required”
#@when “user sets “How many presentations” as “1””
#@when “user sets  “# of tests?” as “2””
#@when “user sets  “# of essays?” as “0””
#@when “user sets “student overall comment about the class “ “No additional Comments””
#@then “a valid review highlighted in green is created”


class ReviewsController < ApplicationController
    # before_action :authenticate_user!, except: [:index, :show]
    
    def new
        @review = current_user.reviews.build
    end
    def create
        @course = Course.find(params[:course_id])
        @review = @course.reviews.create(review_params)
        redirect_to course_path(@course)
    end
    
    def destroy
       @course = Course.find(params[:course_id])
       @review = @course.reviews.find(params[:id])
       @review.destroy
       redirect_to course_path(@course)
    end
    
    private
    def review_params
        params.require(:review).permit(:professor_name, :overall_rating, :professor_rating, :difficulty_rating, :language, :textbook_req, :computer_req, :presentations, :tests, :essays, :comment)
    end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/helpers/courses_helper.rb
module CoursesHelper
end

webapp/app/helpers/home_helper.rb
module HomeHelper
end

webapp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

webapp/app/views/courses/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RateMyCCI - Courses</title>

  <!-- loads controller specific assets-->
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag params[:controller] %>
</head>

<body>

<!-- Page Content -->
  <div class="container-classes">

      <div class="col-lg-12 text-center">
        <h1 class="mt-5">CCI Courses</h1>
        <!-- <p class="lead">Complete with pre-defined file paths and responsive navigation!</p> -->
         
          <ul class="navbar-nav ml-auto">
          <% @courses.each do |course| %>
            <li class="courses">
              <%= link_to course.course_name, course_path(course) %>
            </li>
          <% end %>
          
      
  <li id="course-add">
  <%= link_to 'Add a new course' , new_course_path %><br>
  </li>
  </ul>
  </div>
  </div>

</body>
</html>

webapp/app/views/courses/new.html.erb
<%= link_to "Home", root_path %><br>
<%= link_to 'Back to Courses', courses_path %>
<h1>Add new course</h1>

<!--'url: articles_path'. courses_path helper tells rails to point the form to send a POST reqest to the route create-->
<%= form_for :course, url: courses_path do |f| %>

    <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    
    
    <%= f.label :course_name, "What is the Course Name?" %>
    <%= f.text_field :course_name %><br>

    <%= f.submit %>
<% end %>

<%= link_to 'Back to Courses', courses_path %>

webapp/app/views/courses/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RateMyCCI - Courses</title>

  <!-- loads controller specific assets-->
  
  <%= stylesheet_link_tag "reviews" %>
  
</head>

<body>

<!-- Page Content -->

  <div class="container-classes">
    <h1>
    <%= @course.course_name %>
    </h1>
        <h1 id="title2">Student Reviews</h1>
        <!-- <p class="lead">Complete with pre-defined file paths and responsive navigation!</p> -->
         
          <ul class="navbar-nav ml-auto">
          <% @course.reviews.each do |review| %>
            <div class="review-block">
              <table style="height: 163px; width: 779px;">
<tbody>
<tr style="height: 36px;">
  <p><strong>Professor Name:&nbsp;</strong><%= review.professor_name %></p>

<td style="width: 354px; text-align: right; height: 36px;"><strong>Overall Rating:</strong></td>
<td class="overall" style="width: 88px; height: 36px; text-align: center;"><%= review.overall_rating %></td>
<td style="width: 634px; text-align: right; height: 36px;"><strong>Programming Language:</strong></td>
<td style="width: 342px; height: 36px; text-align: center;"><%= review.language %></td>
<td style="width: 311px; height: 36px; text-align: right;"><strong># of Presentations:</strong></td>
<td style="width: 345px; height: 36px; text-align: center;"><%= review.presentations %></td>
</tr>
<tr style="height: 36px;">
<td style="width: 354px; text-align: right; height: 36px;"><strong>Professor Rating:</strong></td>
<td style="width: 88px; height: 36px; text-align: center;"><%= review.professor_rating %></td>
<td style="width: 634px; text-align: right; height: 36px;"><strong>Textbook Required?:</strong></td>
<td style="width: 342px; height: 36px; text-align: center;"><%= review.textbook_req %></td>
<td style="width: 311px; height: 36px; text-align: right;"><strong># of Tests:</strong></td>
<td style="width: 345px; height: 36px; text-align: center;"><%= review.tests %></td>
</tr>
<tr style="height: 36px;">
<td style="width: 354px; text-align: right; height: 36px;"><strong>Difficulty Rating:</strong></td>
<td style="width: 88px; height: 36px; text-align: center;"><%= review.difficulty_rating %></td>
<td style="width: 634px; text-align: right; height: 36px;"><strong>Laptop Required?</strong></td>
<td style="width: 342px; height: 36px; text-align: center;"><%= review.computer_req %></td>
<td style="width: 311px; height: 36px; text-align: right;"><strong># of Essays:</strong></td>
<td style="width: 345px; height: 36px; text-align: center;"><%= review.essays %></td>
</tr>

</tr>
</tbody>
</table>
<br>
<strong>Comment:</strong>
<%= review.comment %>
</div>
<% end %>
          
      <div class="reviewform">
  <h3>Add a review:</h3>
<%= form_for([@course, @course.reviews.build]) do |f| %>
    <%= f.label :professor_name, "What is your professor's name?" %>
    <%= f.select :professor_name, ['Select Professor', 'Alberto Gonzalez', 'Cara Alberto Jokell', 'Charles Chuck Lane', 'Dale-Marie Cretia Anne Wilson', 'Daniel Joseph Jugan', 'Debarati Basu', 'Julio Cesar Bahamon', 'Lijuan Cao', 'Lorrie J Lehmann', 'Marlon Mejias', 'N. Rich Nguyen', 'Nadia Abusaymeh Najjar', 'Norman Bruce Long', 'Sara Houser Scott'] %><br>
    <!--1-5 overall course rating-->
    <%= f.label :overall_rating, "What is your overall rating of the class?" %>
    <%= f.select :overall_rating, [10,9,8,7,6,5,4,3,2,1] %><br>
    <!--1-5 prof review-->
    <%= f.label :professor_rating, "" %>
    <%= f.select :professor_rating, [10,9,8,7,6,5,4,3,2,1] %><br>
    <!--1-5 difficulty rating-->
    <%= f.label :difficulty_rating, "" %>
    <%= f.select :difficulty_rating, [10,9,8,7,6,5,4,3,2,1] %><br>
    <!--programming language?-->
    <%= f.label :language, "What was the programming language?" %>
    <%= f.select :language, ['N/A', 'c++', 'c#', 'MySQL', 'python'] %><br>
    <!--Textbook required?-->
    <%= f.label :textbook_req, "Is the textbook required? Check for yes." %>
    <%= f.check_box :textbook_req %><br>
    <!--is computer required?-->
    <%= f.label :computer_req, "Is a computer required to bring to class?" %>
    <%= f.check_box :computer_req %><br>
    <!--# of presentations?-->
    <%= f.label :presentations, "How many presentations?" %>
    <%= f.text_field :presentations %><br>
    <!--# of tests?-->
    <%= f.label :tests, "How many tests?" %>
    <%= f.text_field :tests %><br>
    <!--# of essays?-->
    <%= f.label :essays, "How many essays?" %>
    <%= f.text_field :essays %><br>
    <!--student overall comment about the class-->
    <%= f.label :comment, "Please leave any helpful details about the class:" %><br>
    <%= f.text_area :comment %><br>
    <!--submit course data-->
    <%= f.submit %>
<% end %>
</div>
    </div>
    
  </div>

</body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
// self executing function here

$(document).ready(function(){
    var x = document.getElementsByClassName("overall");
    console.log(x[0].innerHTML);
    var numReviews = $('.review-block').length
    console.log(numReviews);
    
    for (i = 0; i < numReviews; i++) {
      if(x[i].innerHTML > 5){
          $(`.review-block:eq(`+i+`)`).css("background-color", "#C2E9CF");
      }
      else{
          $(`.review-block:eq(`+i+`)`).css("background-color", "#ECD2D7");
      }
    }
    
    

}); //end ready

</script>

webapp/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RateMyCCI - Courses</title>

  <!-- loads controller specific assets-->
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag params[:controller] %>
</head>

<body>

<!-- Page Content -->
  <div class="container-classes">
        <h1>RateMyCCI</h1>
        <p>Check out the <%= link_to 'courses', controller: 'courses' %> people have reviewed!</p>
        <p>Github: <a href="https://github.com/antonybstack/RateMyCCI">https://github.com/antonybstack/RateMyCCI</a> </a></p>
        <p>Software Engineering ITSC-3155-102</p>
        <ul id="testy">Team Members:
            <li>Micah Langford - mlangfo1@uncc.edu</li>
            <li>Antony Blyakher - ablyakhe@uncc.edu</li>
            <li>Delaney Mizell - dmizell1@uncc.edu</li>
        </ul>
        <p>Summary: Webapp that aggregates ratings and reviews of CCI classes for CCI students</p>
        <p>This project idea’s goal is to impact the CCI students and facualty at UNCC in a postive way</p>
        <p></p>
</p>
  </div>

</body>
</html>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyCCI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "bootstrap.min.css" %> 
    <%= stylesheet_link_tag "bootstrap.css" %> 
    
    <!-- Bootstrap core JavaScript -->
    <%= javascript_include_tag 'jquery.slim.min.js' %>
    <%= javascript_include_tag 'bootstrap.bundle.min.js' %>
    <%= javascript_include_tag 'bootstrap.bundle.js' %>
  </head>

  <body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a href="/"><img src="/assets/RateMyCCI.png" width="92.8125" height="70" class="navbar-brand"></a>
      <a class="navbar-brand" href="/">RateMyCCI</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, {:class=>"nav-link"}%>
          </li>
          <li class="nav-item">
            <%= link_to 'Courses', courses_path, {:class=>"nav-link"} %>
              
            </a>
          </li>
          
            <% if user_signed_in? == false %>
                <li class="nav-item">
                  <%= link_to "Sign In", new_user_session_path, {:class=>"nav-link"} %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign Up", new_user_registration_path, {:class=>"nav-link"} %>
                </li>
            <% else %> 
                <li class="nav-item">
                  
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class=>"nav-link" %>
                </li>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <% if user_signed_in? == true %>
  Welcome <strong><%= current_user.email %></strong>! &nbsp
  <% end %>
  
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    
    <%= yield %>

  </body>
</html>